version: '3.8'

services:
  openhab:
    image: "rongyj/openhab-2.5.7-alphine"
    restart: always
    container_name: "openhab"
    tty: true
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8101:8101"
      - "1099:1099"
      - "44444:44444"
    volumes:
      - "~/openhab/addons:/openhab/addons"
      - "~/openhab/conf:/openhab/conf"
      - "~/openhab/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      USER_ID: ${UID}
      GROUP_ID: ${GID}
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/New_York"
